### ISSUE TITLE
count parameter

### ISSUE THREAD

**Issue by mnjd** [liyapo/RailroadGraph#1]
As the code is written, it is up to the user to input the parameter "count". This parameter is crucial as it is the one which stops creating new routes if the "maximum number of stops" is reached. The "max num of stops" is defined as 2^count. 

From the user point of view, the "maximum number of stops" can be easily understood but one has to go through the code to correctly input the "count" parameter. 

You could, rather than asking the user to input "count", ask the user to give the "maximum number of stops" and compute in the code yourself, the "count" parameter.

**Comment by liyapo** [comment]
well, as it is not required as an input, I decided to simply fix it in the program. I understand that it is not the proper way to do, but for this task I guess I can leave it this way
